swagger: "2.0"
info:
  title: Research Pillars API
  version: "1.0"
  contact:
    name: Research Enablement Team
    url: https://data4life.care
tags:
  - name: Programs
  - name: Surveys
  - name: Questionnaires
  - name: Routines
  - name: Displays
  - name: Consents
  - name: Utilities
  - name: Checks
consumes:
  - application/json
produces:
  - application/json
paths:
  /checks/liveness:
    get:
      operationId: Checks_Liveness
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticChecksResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Checks
  /checks/readiness:
    get:
      operationId: Checks_Readiness
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticChecksResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Checks
  /programs:
    get:
      operationId: Programs_GetPrograms
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetProgramsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Programs
  /programs/{name}:
    get:
      operationId: Programs_GetProgram
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetProgramResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Programs
  /programs/{name}/data:
    get:
      operationId: Programs_GetProgramData
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetProgramDataResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Programs
  /programs/{name}/updatedAt:
    get:
      operationId: Programs_GetProgramUpdatedAt
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetProgramUpdatedAtResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Programs
  /programs/{programName}/consents:
    get:
      operationId: Consents_GetConsents
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetConsentsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
      tags:
        - Consents
  /programs/{programName}/consents/{name}:
    get:
      operationId: Consents_GetConsent
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetConsentResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Consents
  /programs/{programName}/consents/{name}/{version}:
    get:
      operationId: Consents_GetConsentVersion
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetConsentVersionResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: version
          in: path
          required: true
          type: integer
          format: int32
      tags:
        - Consents
  /programs/{programName}/displays:
    get:
      operationId: Displays_GetDisplays
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetDisplaysResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
      tags:
        - Displays
  /programs/{programName}/displays/{name}:
    get:
      operationId: Displays_GetDisplay
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetDisplayResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Displays
  /programs/{programName}/questionnaires:
    get:
      operationId: Questionnaires_GetQuestionnaires
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetQuestionnairesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: language
          in: query
          required: false
          type: string
      tags:
        - Questionnaires
  /programs/{programName}/questionnaires/{name}:
    get:
      operationId: Questionnaires_GetQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetQuestionnaireResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
        - name: language
          in: query
          required: false
          type: string
      tags:
        - Questionnaires
  /programs/{programName}/routines:
    get:
      operationId: Routines_GetRoutines
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetRoutinesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
      tags:
        - Routines
  /programs/{programName}/routines/{name}:
    get:
      operationId: Routines_GetRoutine
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetRoutineResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Routines
  /programs/{programName}/surveys:
    get:
      operationId: Surveys_GetSurveys
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetSurveysResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
      tags:
        - Surveys
  /programs/{programName}/surveys/{name}:
    get:
      operationId: Surveys_GetSurvey
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticGetSurveyResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: programName
          in: path
          required: true
          type: string
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Surveys
  /utilities/proxy:
    post:
      operationId: Utilities_Proxy
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/staticProxyResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/staticProxyRequest'
      tags:
        - Utilities
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  protobufNullValue:
    type: string
    enum:
      - NULL_VALUE
    default: NULL_VALUE
    description: |-
      `NullValue` is a singleton enumeration to represent the null value for the
      `Value` type union.

       The JSON representation for `NullValue` is JSON `null`.

       - NULL_VALUE: Null value.
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  staticChecksResponse:
    type: object
    properties:
      response:
        type: string
  staticGetConsentResponse:
    type: object
    properties:
      consents:
        type: array
        items:
          type: object
  staticGetConsentVersionResponse:
    type: object
    properties:
      consent:
        type: object
  staticGetConsentsResponse:
    type: object
    properties:
      consents:
        type: array
        items:
          type: object
  staticGetDisplayResponse:
    type: object
    properties:
      display:
        type: object
  staticGetDisplaysResponse:
    type: object
    properties:
      displays:
        type: array
        items:
          type: object
  staticGetProgramDataResponse:
    type: object
    properties:
      program:
        type: object
      surveys:
        type: array
        items:
          type: object
      questionnaires:
        type: array
        items:
          type: object
      consents:
        type: array
        items:
          type: object
      routines:
        type: array
        items:
          type: object
      displays:
        type: array
        items:
          type: object
  staticGetProgramResponse:
    type: object
    properties:
      program:
        type: object
  staticGetProgramUpdatedAtResponse:
    type: object
    properties:
      updatedAt:
        type: string
  staticGetProgramsResponse:
    type: object
    properties:
      programs:
        type: array
        items:
          type: object
  staticGetQuestionnaireResponse:
    type: object
    properties:
      questionnaire:
        type: object
  staticGetQuestionnairesResponse:
    type: object
    properties:
      questionnaires:
        type: array
        items:
          type: object
  staticGetRoutineResponse:
    type: object
    properties:
      routine:
        type: object
  staticGetRoutinesResponse:
    type: object
    properties:
      routines:
        type: array
        items:
          type: object
  staticGetSurveyResponse:
    type: object
    properties:
      survey:
        type: object
  staticGetSurveysResponse:
    type: object
    properties:
      surveys:
        type: array
        items:
          type: object
  staticProxyRequest:
    type: object
    properties:
      target:
        type: string
      params:
        type: object
  staticProxyResponse:
    type: object
    properties:
      body:
        type: object
